name: "github pull request reminder"

inputs:
  active:
    description: Determines whether the action will run.
    required: false
    default: true
  channel:
    description: The channel you want messages posted to
    required: false
    default: \#general
  slack-auth:
    description: The OAuth token of the slack bot, stored as repo secret
    required: true
    default: "you didn't supply a token"
  repo-token:
    description: this is an authentication token
    required: true
    default: no token

runs:
  using: "node12"
  main: "dist/index.js"
